# Generated by Django 2.2.7 on 2020-04-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=None, verbose_name='Event Date'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='time_period',
            field=models.CharField(choices=[('JUST_NOW', 'JUST_NOW'), ('HOUR', 'HOUR'), ('DAY', 'DAY'), ('WEEK', 'MONTH')], default='JUST_NOW', max_length=15, verbose_name='Time period for sending a notification'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to_send_invitations',
            field=models.DateTimeField(verbose_name='date and time to send invitation'),
        ),
    ]
